name: PlayerCharacters
main: override.studio.strlantian.PlayerCharacters
version: 1.0
api-version: 1.18
author: STRlantian
commands:
  character:
    description: Player Characters
    usage: /character <function>
    aliases:
      - cha